packages:
  - backend
  - frontend

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - lefthook
  - prisma
  - unrs-resolver
