packages:
  - backend
  - frontend
  - database
  - infrastructure
  - docs

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver
