packages:
  - backend
  - frontend
  - database
  - infrastructure
  - docs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver

injectWorkspacePackages: true
