# Образ для разработки backend
FROM node:24.14.1-alpine3.23 AS dev

# Переменные окружения для pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PNPM_DISABLE_SELF_UPDATE_CHECK=true
ENV PNPM_STORE_PATH=/pnpm/store
ENV CI=true

WORKDIR /app

# Включаем pnpm через Corepack
RUN corepack enable

# Копируем конфигурацию workspace и lockfile
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm fetch

# Копируем package.json зависимых пакетов
COPY backend/package.json ./backend/

# Устанавливаем зависимости backend из локального кэша
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --offline --frozen-lockfile --filter @mse/backend

# Копируем исходный код backend
COPY backend ./backend

EXPOSE 3000

# Запуск NestJS в watch-режиме
CMD ["sh", "-c", "pnpm --filter @mse/backend db:deploy && pnpm --filter @mse/backend start:dev"]
