name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        task: [format:check, lint, typecheck, test]

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: 'Fetch Latest Main Branch'
        run: git fetch origin main --depth=1

      - name: 'Setup Project'
        uses: ./.github/actions/setup

      - name: 'Run Checks'
        run: pnpm --filter "...[origin/main]" --filter "!mse1h2026-project" -r --if-present ${{ matrix.task }}

  deploy:
    name: deploy (${{ matrix.target }})
    needs: [check]
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [local, docker]

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: 'Fetch Latest Main Branch'
        run: git fetch origin main --depth=1

      - name: 'Setup Project'
        if: matrix.target == 'local'
        uses: ./.github/actions/setup

      - name: 'Build Project'
        if: matrix.target == 'local'
        run: pnpm run build

      - name: Enable BuildKit
        if: matrix.target == 'docker'
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
          echo "COMPOSE_DOCKER_CLI_BUILD=1" >> $GITHUB_ENV

      - name: 'Build Docker images'
        if: matrix.target == 'docker'
        run: docker compose build
