name: CI
on: push
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm lint
