name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        task: [format:check, lint, typecheck]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - run: git fetch origin main --depth=1
      - uses: ./.github/actions/setup
      - run: pnpm --filter "...[origin/main]" -r --if-present ${{ matrix.task }}

  build:
    needs: [check]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - run: git fetch origin main --depth=1
      - uses: ./.github/actions/setup
      - run: pnpm --filter "...[origin/main]" -r build
